"""
Django settings for socialcontact project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jsr+=uorm)j$0+q^5n1!cr%7%dkm*oi6$h&xbd=4l9qn2z(@f-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '51.20.176.13', 'ddivesocial.com', 'www.ddivesocial.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'social_media_post',
    'social_django'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',  # social auth

]

ROOT_URLCONF = 'socialcontact.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        # 'DIRS': [BASE_DIR,"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect', 
            ],
        },
    },
]

WSGI_APPLICATION = 'socialcontact.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]




MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CRISPY_TEMPLATE_PACK = 'bootstrap4'


# FACEBOOK_ACCESS_TOKEN = 'EAAFqhDJUYBQBO5GM2n1AyJzbp1lcedOwfMs057ZC8zz61qLkiZCN5MDxMp2byZAzrjReqMZAaLJLTx6HVnJX1Rlz01CMLJN8YiZBBz5gYkvrFk4ZCo3LkpDYevbFdeBZB3WQGhZAbAvQJBCCS8ZC3yPHoQo9x6aNUqzV0NTlvgvtpUkZA6DfzrZA0OsVQmNz9lQkFbZAiFx4ZCZC47sgrzLR5ijIZBbPVbOIbxcw88gfWdCdChXZA9mpRWAH0zq3UZCO1VgS7cixdOQZDZD'

# FACEBOOK_APP_ID = 398590989328404

# FACEBOOK_APP_SECRET = '4483a0c42d7546d5b92fadf31f8d9ba6'


# SOCIAL_AUTH_FACEBOOK_KEY = '899655998546033'  
# SOCIAL_AUTH_FACEBOOK_SECRET = '9bec522a41ebd556ff1957efdefb5020' ------finl

# SOCIAL_AUTH_FACEBOOK_KEY = "1164193547880922"
# SOCIAL_AUTH_FACEBOOK_SECRET = "8d9e299cd4799be7509b14598577c2fe" --localdetails pri

SOCIAL_AUTH_FACEBOOK_KEY = "1771703993310026"
SOCIAL_AUTH_FACEBOOK_SECRET = "ea6e4300df0e6087d9d6df63ac12bd84"


# SOCIAL_AUTH_FACEBOOK_KEY = '748250723966913'  
# SOCIAL_AUTH_FACEBOOK_SECRET = 'fa32ab5a98154e06de6460d131e38d72' 


AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.github.GithubOAuth2',

    'django.contrib.auth.backends.ModelBackend',


    'social_core.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)


SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = 'login2'

# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_URL = 'logout'
# LOGOUT_REDIRECT_URL = 'login'


# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_URL = 'logout'
# LOGOUT_REDIRECT_URL = 'login'

'''
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '77jxi0297t51d6'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'cyGaBhJv2wh2LKpS'
'''
BASE_URL = "https://ddivesocial.com"
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '775avibli3iksz'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'T9UilMukOzwU5Eup'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE  = "w_member_social,email,profile,r_basicprofile,openid,w_organization_social,r_organization_social,r_organization_admin,rw_organization_admin"
LINKEDIN_REDIRECT_URL = f'{BASE_URL}/linkedin/callback/access/'
LINKEDIN_BASE_URL = "https://www.linkedin.com/oauth/v2/authorization"
LINKEDIN_ACCESS_URL = "https://www.linkedin.com/oauth/v2/accessToken"
