# Generated by Django 5.0.2 on 2024-02-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='PostList',
        ),
    ]
