# Generated by Django 5.0.2 on 2024-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_postlist_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlist',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
