# Generated by Django 5.0.2 on 2024-02-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_postlist_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostList',
        ),
    ]
