# Generated by Django 5.0.2 on 2024-02-21 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0002_useraccesstoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesstoken',
            name='token',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='useraccesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
