# Generated by Django 5.0.2 on 2024-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_post', '0003_alter_useraccesstoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
